Feat/backend auth setup
9j3/chai pull request #23
Opened 2022-08-14 18:05 UTC by 9j3

2022-08-14 19:02 UTC, bariod requested changes

2022-08-14 19:02 UTC, bariod commented on packages/api/src/requests.ts
> +  @IsNotEmpty({ message: 'An username is required' })
```suggestion
  @IsNotEmpty({ message: 'A username is required' })
```

2022-08-14 19:02 UTC, bariod commented on packages/api/test/e2e/app/app.e2e-spec.ts
> +import {ApplicationModule} from "../../../src/app.module";
run the formatter on this file
```suggestion
import { ApplicationModule } from "../../../src/app.module";
```

2022-08-14 19:02 UTC, bariod commented on packages/api/test/e2e/app/app.e2e-spec.ts
> +            .send({username: 'usrnamenotavalibl', password: 'pws'})
```suggestion
            .send({username: 'usrnamenotavalible', password: 'pws'})
```

2022-08-14 19:02 UTC, bariod commented on packages/api/http/REGISTER.http
> +  "username": "brunos",
```suggestion
  "username": "bruno",
```
intentional?

2022-08-14 19:27 UTC, 9j3 commented on packages/api/src/modules/auth/auth.controller.ts
> +   *
These are required for upcoming API documentation with swagger

2022-08-14 19:29 UTC, 9j3 commented on packages/api/test/e2e/app/app.e2e-spec.ts
> +import {ApplicationModule} from "../../../src/app.module";
These are .spec files (for testing) which are ignored by ESLint. I can add them if you wan't but atm I think it doesn't matter that much :)

2022-08-14 19:32 UTC, 9j3 commented on packages/api/src/modules/auth/token.service.ts
> +
Our style guide allows either no line or one line :)

2022-08-15 14:33 UTC, bariod approved these changes

2022-08-15 14:33 UTC, bariod commented on packages/api/test/e2e/app/app.e2e-spec.ts
> +            .send({username: 'usrnamenotavalible', password: 'pws'})
```suggestion
            .send({username: 'usernamenotavalible', password: 'pws'})
```
aaaah sryyy

2022-08-15 16:10 UTC, merged