add WIP chat view
9j3/chai pull request #29
Opened 2022-08-28 12:56 UTC by bariod

some useless format changes snuck into this one as well..

2022-08-28 12:57 UTC, bariod commented on packages/app/src/components/InputBox.vue
> +    this.$emit('sendMessage', input.value) // todo: es5 function has own this context
I'm currently having a problem emitting, as the "this" in this function is not the "global" one.. 
```
Uncaught TypeError: Cannot read properties of undefined (reading '$emit')
```

2022-08-28 13:25 UTC, bariod commented
WIP stuff:
- the css is still a mix of your changes and mine :D
- messages still have to be sent to backend
- top bar (with search and user icon) is also not included

2022-08-28 15:07 UTC, 9j3 requested changes

2022-08-28 15:07 UTC, 9j3 commented on packages/app/src/components/InputBox.vue
> +}
see https://vuejs.org/guide/components/events.html#usage-with-v-model . Emitting events in vue 3 with the composition api is a bit diffrent in context to vue 2.

2022-08-28 15:07 UTC, 9j3 commented on packages/app/src/views/HomeWrapper.vue
> +}
this logic should be handlet either in a store action or with the socket.io instance. You can leave it for the moment, but notice this ;)

2022-08-28 15:07 UTC, 9j3 commented on packages/app/src/components/ChatDaySeparator.vue
> +})
We dont like Dates as a String. Instead, pass dateString as a pure Date object and use the provided date formatting functions of Js: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

2022-08-28 15:09 UTC, 9j3 commented on packages/app/src/components/InputBox.vue
> +    this.$emit('sendMessage', input.value) // todo: es5 function has own this context
See: https://vuejs.org/guide/components/events.html#usage-with-v-model

2022-08-28 21:51 UTC, 9j3 commented
@bariod I've done some operational work as announced. This contains switching to pnpm from yarn and fixing prettier/eslint. It now works like a charm 😄

2022-08-28 22:06 UTC, 9j3 commented
@bariod I also had to pin the eslint module to version 8.22.0 because there were changes to the api of eslint. However, this should not affect you, since you use vscode - the whole thing is a bug of webstorm: https://youtrack.jetbrains.com/issue/WEB-57089/ESLint823-TypeError-thislibOptionsparse-is-not-a-function

2022-08-29 16:46 UTC, bariod commented on packages/app/src/components/ChatDaySeparator.vue
> +})
Who is "we"? 🌚

2022-08-29 17:34 UTC, 9j3 commented on packages/app/src/components/ChatDaySeparator.vue
> +})
The Matrix Agents 🌚

2022-08-29 18:04 UTC, bariod commented on packages/app/src/views/HomeWrapper.vue
> +                  x-text="user.email"
I don't even know what that was for. It's still a leftover from the initial version.

2022-08-29 18:21 UTC, 9j3 approved these changes

2022-08-29 18:21 UTC, merged