34 ondisconnect should remove user from store
9j3/chai pull request #37
Opened 2022-09-04 16:35 UTC by 9j3

2022-09-04 17:32 UTC, bariod requested changes

2022-09-04 17:32 UTC, bariod commented on packages/api/src/modules/chat/chat.gateway.ts
> +    // notify all connected client's that there is a new leave
```suggestion
    // notify all connected clients that there is a new disconnect
```

2022-09-04 17:32 UTC, bariod commented on packages/api/src/modules/chat/chat.gateway.ts
> +    // notify all connected client's that there is a new connection
```suggestion
    // notify all connected clients that there is a new connection
```

2022-09-04 17:32 UTC, bariod commented on packages/api/src/modules/chat/chat.gateway.ts
> +    // tell other clients that client is typing
```suggestion
    // tell other clients that client has stopped typing
```

2022-09-04 17:32 UTC, bariod commented on packages/app/src/views/HomeView.vue
> +    }, 1000);
Might wanna increase this number eventually. But we'll see in testing.

2022-09-04 17:32 UTC, bariod commented on packages/app/src/views/HomeView.vue
> +          <p class="text-xs font-medium text-gray-400">TEXT-CHANNELS</p>
Looks like we have a formatting issue once again in the vue files...

2022-09-06 14:38 UTC, 9j3 commented on packages/app/src/views/HomeView.vue
> +          <p class="text-xs font-medium text-gray-400">TEXT-CHANNELS</p>
Done

2022-09-06 15:51 UTC, bariod approved these changes

2022-09-06 16:28 UTC, merged